config/routes.rb
Rails.application.routes.draw do
  root 'ads#index'
  resources :ads

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

	def show
		@ad = Ad.find_by_id(params[:id])
	end

	def index

		@ads = Ad.all
	end

	def new 

		@ad = Ad.new
		
	end

  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
 end

  private

   def ad_params
      params.require(:ad).permit(:name, :description, :price, :seller_id, :email, :img_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
<div class = "field">
<%=f.label "Nome" %><br>
<%=f.text_field :name %>
</div>


<div class = "field">
<%=f.label "Descrição" %><br>
<%=f.text_field :description %>
</div>


<div class = "field">
<%=f.label "Preço" %><br>
<%=f.text_field :price %>
</div>


<div class = "field">
<%=f.label "Vendedor" %><br>
<%=f.text_field :seller_id %>
</div>


<div class = "field">
<%=f.label "Email" %><br>
<%=f.text_field :email %>
</div>


<div class = "field">
<%=f.label "Imagem" %><br>
<%=f.text_field :img_url %>
</div>

<div class="actions">
<%= f.submit "Salvar anuncio" %>
</div>

<% end% %>

app/views/ads/index.html.erb
<<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>
	 <H1>Todos os anuncios</H1>
	 <ul>
	 	<% @ads.each do |ad| %>
	 	 	<li> <%= link_to ad.name, ad %> </li>
     	<% end %>

	 </ul>
	 	<%= link_to 'Novo Anuncio', new_ad_path %>
	</body>
</html>

app/views/ads/new.html.erb
<<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<h1>Novo Anuncio</h1>
		<%= render 'form' %>
	</body>
</html>

app/views/ads/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<p>Nome: <%= @ad.name %></p>
		<p>Descrição: <%= @ad.description %></p>
		<p>Preço: <%= @ad.price %></p>
		<p>Id Vendedor: <%= @ad.seller_id %></p>
		<p>Email: <%= @ad.email %></p>
		<p><img src= "<%= @ad.img_url %>"></p>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Ads: <%= controller.action_name %></title>
    <%= stylesheet_link_tag 'application.css' %>
</head>
<body>
    <div id="wrapper">
		<div id="header">
			<div>

				<h1>MeBay</h1>
				<ul id="nav">
					<li><a href="/ads/">Todos os anuncios</a></li>
				</ul>
			</div>
		</div>

		<div id="content">
		  <%= yield %>
		</div>
		<div id="clearfooter"></div>
    </div>
	<div id="footer"></div>
</body>
</html>